# Generated by Django 3.1.2 on 2020-10-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0002_auto_20201021_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
