# Generated by Django 3.1.2 on 2020-10-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0004_pricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name_plural': 'price changes'},
        ),
    ]
